// Generated by tools/ttf_to_header.py -- do not edit by hand.
// Charis SIL (c) SIL International, licensed under the SIL Open Font
// License 1.1. See src/text/fonts/OFL.txt.

#pragma once
#include <stdint.h>

extern const uint8_t kCharisRegular[27532];
extern const uint8_t kCharisBold[27880];
extern const uint8_t kCharisItalic[28904];
extern const uint8_t kCharisBoldItalic[28996];

