#!/usr/bin/env python3
"""Turns a TrueType font into an Adafruit GFX font header (GFXfont).

    python3 tools/make_gfx_font.py FreeSerif.ttf 8 FreeSerif8pt7b > reader/fonts/FreeSerif8pt7b.h

Does what Adafruit's fontconvert does, with Pillow instead of a C build:
ASCII 0x20-0x7E, sizes in points at 141 DPI (so "8pt" here matches the
library's own FreeSerif9pt7b, 12pt7b, ... scale), 1 bit per pixel with no
anti-aliasing, and glyph bitmaps packed bit-continuously. Needs Pillow
(python3 -m pip install pillow).
"""
import sys

from PIL import Image, ImageDraw, ImageFont

DPI = 141
FIRST, LAST = 0x20, 0x7E


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    path, points, name = sys.argv[1], float(sys.argv[2]), sys.argv[3]
    font = ImageFont.truetype(path, round(points * DPI / 72))

    bitmap = bytearray()
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = round(font.getlength(ch))
        # Render without anti-aliasing on a roomy canvas, then crop to the
        # pixels actually set: that is the glyph's true box.
        pad = 2 * font.size
        canvas = Image.new("1", (advance + 2 * pad, 2 * pad), 0)
        draw = ImageDraw.Draw(canvas)
        draw.fontmode = "1"  # no anti-aliasing: the panel is black and white
        draw.text((pad, pad), ch, font=font, fill=1, anchor="ls")
        box = canvas.getbbox()
        offset = len(bitmap)
        if box:
            # Relative to the pen on the baseline. Adafruit's fontconvert puts
            # glyphs 1 px lower (yOffset = 1 - bitmap_top); match it so these
            # fonts line up with the library's own.
            x0, y0 = box[0] - pad, box[1] - pad + 1
            w, h = box[2] - box[0], box[3] - box[1]
            img = canvas.crop(box)
            bits = [img.getpixel((x, y)) for y in range(h) for x in range(w)]
            for i in range(0, len(bits), 8):
                byte = 0
                for j, b in enumerate(bits[i:i + 8]):
                    if b:
                        byte |= 0x80 >> j
                bitmap.append(byte)
        else:
            w = h = x0 = y0 = 0
        glyphs.append((offset, w, h, advance, x0, y0, code))

    ascent, descent = font.getmetrics()
    y_advance = ascent + descent

    print(f"// {name}: generated by tools/make_gfx_font.py from {path.split('/')[-1]}, "
          f"{points:g}pt at {DPI} DPI.")
    print("// GNU FreeFont, GPLv3 with the font exception (embedding in a program is allowed).")
    print("#pragma once")
    print("#include <Adafruit_GFX.h>\n")
    print(f"const uint8_t {name}Bitmaps[] PROGMEM = {{")
    for i in range(0, len(bitmap), 12):
        print("  " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 12]) + ",")
    print("};\n")
    print(f"const GFXglyph {name}Glyphs[] PROGMEM = {{")
    for offset, w, h, adv, xo, yo, code in glyphs:
        label = "' '" if code == 0x20 else ("'\\\\'" if chr(code) == "\\" else f"'{chr(code)}'")
        print(f"  {{ {offset}, {w}, {h}, {adv}, {xo}, {yo} }},  // 0x{code:02X} {label}")
    print("};\n")
    print(f"const GFXfont {name} PROGMEM = {{ (uint8_t *){name}Bitmaps, (GFXglyph *){name}Glyphs,")
    print(f"                                0x{FIRST:02X}, 0x{LAST:02X}, {y_advance} }};")


if __name__ == "__main__":
    main()
