#!/usr/bin/env python3
"""Turns a cover image into a 1-bit C array for the e-reader.

    python3 tools/make_cover.py cover.jpg pride

writes reader/covers/pride.h containing COVER_PRIDE.

The panel is 1 bit per pixel, so the image is Floyd-Steinberg dithered rather
than thresholded: on e-ink that choice is the difference between a cover that
reads as artwork and one that reads as a blob.

Bit convention, matching reader/cover.h: 1 = ink (black), MSB first, each row
padded to whole bytes.
"""
import argparse
import pathlib

from PIL import Image

COVER_W, COVER_H = 204, 306
ROW_BYTES = (COVER_W + 7) // 8


def pack(img: Image.Image) -> bytes:
    out = bytearray(ROW_BYTES * COVER_H)
    for y in range(COVER_H):
        for x in range(COVER_W):
            # Mode "1": 0 is black. Our arrays use 1 for ink.
            if img.getpixel((x, y)) == 0:
                out[y * ROW_BYTES + x // 8] |= 0x80 >> (x % 8)
    return bytes(out)


def emit(data: bytes, slug: str) -> str:
    name = f"COVER_{slug.upper()}"
    lines = [
        f"// Generated by tools/make_cover.py. Do not edit by hand.",
        f"// {COVER_W} x {COVER_H}, 1bpp, 1 = ink, MSB first.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const uint8_t {name}[] = {{",
    ]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"  {chunk},")
    lines += ["};", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("image")
    parser.add_argument("slug", help="file and symbol name, e.g. 'pride'")
    parser.add_argument(
        "--out-dir",
        default=str(pathlib.Path(__file__).parent.parent / "reader" / "covers"),
    )
    args = parser.parse_args()

    img = Image.open(args.image).convert("L")
    img = img.resize((COVER_W, COVER_H), Image.LANCZOS)
    img = img.convert("1")  # Floyd-Steinberg by default

    out_dir = pathlib.Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{args.slug}.h"
    path.write_text(emit(pack(img), args.slug))
    print(f"wrote {path} ({ROW_BYTES * COVER_H} bytes)")


if __name__ == "__main__":
    main()
