#!/usr/bin/env python3
"""Subset TTFs and emit them as C arrays for the ESP32 build.

The ESP32 memory-maps flash, so stb_truetype can read a font placed in
.rodata directly with no RAM cost. Full Charis faces are ~880KB each because
of their minority-language coverage; subsetting to the characters an English
EPUB actually uses brings that down by more than an order of magnitude.

Usage:
    python3 tools/ttf_to_header.py \
        --regular    path/to/Charis-Regular.ttf \
        --bold       path/to/Charis-Bold.ttf \
        --italic     path/to/Charis-Italic.ttf \
        --bolditalic path/to/Charis-BoldItalic.ttf \
        --out-dir    src/text/fonts
"""

import argparse
import io
import os

from fontTools import subset
from fontTools.ttLib import TTFont


def charset():
    """Codepoints worth keeping for English-language EPUBs."""
    cps = set()
    cps.update(range(0x20, 0x7F))  # ASCII printable
    cps.update(range(0xA0, 0x100))  # Latin-1 supplement
    cps.update(range(0x100, 0x180))  # Latin Extended-A, for European names
    cps.update(
        [
            0x2010,  # hyphen
            0x2011,  # non-breaking hyphen
            0x2013,  # en dash
            0x2014,  # em dash
            0x2018,  # left single quote
            0x2019,  # right single quote / apostrophe
            0x201A,
            0x201C,  # left double quote
            0x201D,  # right double quote
            0x201E,
            0x2020,  # dagger
            0x2021,  # double dagger
            0x2022,  # bullet
            0x2026,  # ellipsis
            0x2030,  # per mille
            0x2039,
            0x203A,
            0x2044,  # fraction slash
            0x2212,  # minus
            0xFB01,  # fi ligature
            0xFB02,  # fl ligature
        ]
    )
    return cps


def subset_font(path):
    font = TTFont(path)

    options = subset.Options()
    # No shaping engine on device, so all OpenType layout is dead weight.
    options.layout_features = []
    options.drop_tables += [
        "GSUB", "GPOS", "GDEF", "BASE", "JSTF", "DSIG", "MATH",
        "hdmx", "VDMX", "LTSH", "PCLT", "vhea", "vmtx", "gasp",
        # stb_truetype ignores TrueType hinting bytecode entirely.
        "fpgm", "prep", "cvt ",
    ]
    options.hinting = False
    options.glyph_names = False
    options.legacy_kern = False
    options.name_IDs = []
    options.name_legacy = False
    options.notdef_outline = False
    options.recalc_bounds = True
    options.prune_unicode_ranges = True

    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=charset())
    subsetter.subset(font)

    buf = io.BytesIO()
    font.save(buf)
    font.close()
    return buf.getvalue()


def emit_array(out, symbol, data):
    out.write(f"alignas(4) const uint8_t {symbol}[{len(data)}] = {{\n")
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
        out.write(f"    {row},\n")
    out.write("};\n\n")


FACES = [
    ("regular", "kCharisRegular"),
    ("bold", "kCharisBold"),
    ("italic", "kCharisItalic"),
    ("bolditalic", "kCharisBoldItalic"),
]


def main():
    ap = argparse.ArgumentParser()
    for name, _ in FACES:
        ap.add_argument(f"--{name}", required=True)
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    header = os.path.join(args.out_dir, "CharisSubset.h")
    source = os.path.join(args.out_dir, "CharisSubset.cpp")

    banner = (
        "// Generated by tools/ttf_to_header.py -- do not edit by hand.\n"
        "// Charis SIL (c) SIL International, licensed under the SIL Open Font\n"
        "// License 1.1. See src/text/fonts/OFL.txt.\n\n"
    )

    blobs = []
    for name, symbol in FACES:
        data = subset_font(getattr(args, name))
        blobs.append((symbol, data))
        print(f"{name:12s} {os.path.getsize(getattr(args, name)):>8d} -> {len(data):>7d} bytes")

    with open(header, "w") as out:
        out.write(banner)
        out.write("#pragma once\n#include <stdint.h>\n\n")
        for symbol, data in blobs:
            out.write(f"extern const uint8_t {symbol}[{len(data)}];\n")
        out.write("\n")

    with open(source, "w") as out:
        out.write(banner)
        out.write('#include "text/fonts/CharisSubset.h"\n\n')
        for symbol, data in blobs:
            emit_array(out, symbol, data)

    total = sum(len(d) for _, d in blobs)
    print(f"total embedded: {total} bytes ({total / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
